export const assetsConstants = {
  ASSETS_FETCH_REQUEST: 'ASSETS_FETCH_REQUEST',
  ASSETS_FETCH_SUCCESS: 'ASSETS_FETCH_SUCCESS',
  ASSETS_FETCH_FAILURE: 'ASSETS_FETCH_FAILURE',
  ASSETS_FILTER_ADDED: 'ASSETS_FILTER_ADDED',
  ASSETS_FILTER_REMOVED: 'ASSETS_FILTER_REMOVED',
};
