export const authConstants = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  LOGIN_REMEMBER: 'USER_LOGIN_REMEMBER',
  LOGOUT: 'USER_LOGOUT',
};
